<?php
$db = new SQLite3("blank_dictionary.db");
$a = "CREATE TABLE IF NOT EXISTS a(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($a);
$b = "CREATE TABLE IF NOT EXISTS b(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($b);
$c = "CREATE TABLE IF NOT EXISTS c(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($c);
$d = "CREATE TABLE IF NOT EXISTS d(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($d);
$e = "CREATE TABLE IF NOT EXISTS e(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($e);
$f = "CREATE TABLE IF NOT EXISTS f(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($f);
$g = "CREATE TABLE IF NOT EXISTS g(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($g);
$h = "CREATE TABLE IF NOT EXISTS h(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($h);
$i = "CREATE TABLE IF NOT EXISTS i(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($i);
$j = "CREATE TABLE IF NOT EXISTS j(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($j);
$k = "CREATE TABLE IF NOT EXISTS k(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($k);
$l = "CREATE TABLE IF NOT EXISTS l(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($l);
$m = "CREATE TABLE IF NOT EXISTS m(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($m);
$n = "CREATE TABLE IF NOT EXISTS n(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($n);
$o = "CREATE TABLE IF NOT EXISTS o(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($o);
$p = "CREATE TABLE IF NOT EXISTS p(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($p);
$q = "CREATE TABLE IF NOT EXISTS q(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($q);
$r = "CREATE TABLE IF NOT EXISTS r(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($r);
$s = "CREATE TABLE IF NOT EXISTS s(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($s);
$t = "CREATE TABLE IF NOT EXISTS t(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($t);
$u = "CREATE TABLE IF NOT EXISTS u(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($u);
$v = "CREATE TABLE IF NOT EXISTS v(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($v);
$w = "CREATE TABLE IF NOT EXISTS w(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($w);
$x = "CREATE TABLE IF NOT EXISTS x(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($x);
$y = "CREATE TABLE IF NOT EXISTS y(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($y);
$z = "CREATE TABLE IF NOT EXISTS z(word TEXT, meaning TEXT, synonym TEXT, antonym TEXT, example TEXT)";
$db->exec($z);
?>